<?xml version="1.0" encoding="utf-8"?><Database Name="PlastiBase" Class="DataModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAMED-PC;Initial Catalog=PlastiBase;Persist Security Info=True;User ID=sa" SettingsObjectName="Plasticore.Properties.Settings" SettingsPropertyName="PlastiBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccountInformation" Member="AccountInformations">
    <Type Name="AccountInformation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContactId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_DefaultCurrency]" Member="_DefaultCurrency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AccountInformation_Quote" Member="Quote" ThisKey="ID" OtherKey="SellerAccountInformationId" Type="Quote" Cardinality="One" />
      <Association Name="AccountInformation_Requisition" Member="Requisition" ThisKey="ID" OtherKey="BuyerAccountInformationId" Type="Requisition" Cardinality="One" />
      <Association Name="Address_AccountInformation" Member="BillingAddress" ThisKey="BillingAddressId" OtherKey="Id" Type="Address" IsForeignKey="true" />
      <Association Name="Contact_AccountInformation" Member="Contact" ThisKey="ContactId" OtherKey="Id" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequisitionItem" Member="RequisitionItems">
    <Type Name="RequisitionItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequisitionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfReleases" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleasePeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryInformationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RequisitionItem_BuyerCondition" Member="BuyerConditions" ThisKey="Id" OtherKey="RequisitionItemId" Type="BuyerCondition" />
      <Association Name="RequisitionItem_QuoteItem" Member="QuoteItems" ThisKey="Id" OtherKey="RequisitionItemId" Type="QuoteItem" />
      <Association Name="RequisitionItem_RequestedQuantity" Member="RequestedQuantities" ThisKey="Id" OtherKey="RequisitionItemId" Type="RequestedQuantity" />
      <Association Name="DeliveryInformation_RequisitionItem" Member="Delivery" ThisKey="DeliveryInformationId" OtherKey="Id" Type="DeliveryInformation" IsForeignKey="true" />
      <Association Name="Requisition_RequisitionItem" Member="Requisition" ThisKey="RequisitionId" OtherKey="Id" Type="Requisition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="[_Country]" Member="_Country" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Address_AccountInformation" Member="AccountInformation" ThisKey="Id" OtherKey="BillingAddressId" Type="AccountInformation" Cardinality="One" />
      <Association Name="Address_DeliveryInformation" Member="DeliveryInformation" ThisKey="Id" OtherKey="DestinationAddressId" Type="DeliveryInformation" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.BuyerCondition" Member="BuyerConditions">
    <Type Name="BuyerCondition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequisitionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Condition" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="RequisitionItem_BuyerCondition" Member="RequisitionItem" ThisKey="RequisitionItemId" OtherKey="Id" Type="RequisitionItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[_Ddt]" Member="_Ddt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdditionalComment" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Contact_AccountInformation" Member="AccountInformation" ThisKey="Id" OtherKey="ContactId" Type="AccountInformation" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryInformation" Member="DeliveryInformations">
    <Type Name="DeliveryInformation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestedDeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[_FOB]" Member="_FOB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DestinationAddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DeliveryInformation_RequisitionItem" Member="RequisitionItem" ThisKey="Id" OtherKey="DeliveryInformationId" Type="RequisitionItem" Cardinality="One" />
      <Association Name="Address_DeliveryInformation" Member="Address" ThisKey="DestinationAddressId" OtherKey="Id" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseOrder" Member="PurchaseOrders">
    <Type Name="PurchaseOrder">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Quote" Member="Quotes">
    <Type Name="Quote">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequisitionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellerAccountNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellerAccountInformationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Quote_QuoteItem" Member="QuoteItems" ThisKey="Id" OtherKey="QuoteId" Type="QuoteItem" />
      <Association Name="AccountInformation_Quote" Member="AccountInformation" ThisKey="SellerAccountInformationId" OtherKey="ID" Type="AccountInformation" IsForeignKey="true" />
      <Association Name="Requisition_Quote" Member="Requisition" ThisKey="RequisitionId" OtherKey="Id" Type="Requisition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuoteItem" Member="QuoteItems">
    <Type Name="QuoteItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuoteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequisitionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuoteItem_SellerCondition" Member="SellerConditions" ThisKey="ID" OtherKey="QuoteItemId" Type="SellerCondition" />
      <Association Name="QuoteItem_QuantityMatrix" Member="QuantityMatrixes" ThisKey="ID" OtherKey="QuoteItemId" Type="QuantityMatrix" />
      <Association Name="Quote_QuoteItem" Member="Quote" ThisKey="QuoteId" OtherKey="Id" Type="Quote" IsForeignKey="true" />
      <Association Name="RequisitionItem_QuoteItem" Member="RequisitionItem" ThisKey="RequisitionItemId" OtherKey="Id" Type="RequisitionItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Requisition" Member="Requisitions">
    <Type Name="Requisition" Modifier="Abstract">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_Type]" Member="_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="BuyerAccountNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyerAccountInformationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deadline" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Requisition_RequisitionItem" Member="Items" ThisKey="Id" OtherKey="RequisitionId" Type="RequisitionItem" />
      <Association Name="Requisition_Quote" Member="Quotes" ThisKey="Id" OtherKey="RequisitionId" Type="Quote" />
      <Association Name="AccountInformation_Requisition" Member="AccountInformation" ThisKey="BuyerAccountInformationId" OtherKey="ID" Type="AccountInformation" IsForeignKey="true" />
      <Type Name="Draft" InheritanceCode="0" IsInheritanceDefault="true" />
      <Type Name="Rfq" InheritanceCode="1" />
    </Type>
  </Table>
  <Table Name="dbo.SellerCondition" Member="SellerConditions">
    <Type Name="SellerCondition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuoteItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Condition" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="QuoteItem_SellerCondition" Member="QuoteItem" ThisKey="QuoteItemId" OtherKey="ID" Type="QuoteItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuantityMatrix" Member="QuantityMatrixes">
    <Type Name="QuantityMatrix">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuoteItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Figure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="QuoteItem_QuantityMatrix" Member="QuoteItem" ThisKey="QuoteItemId" OtherKey="ID" Type="QuoteItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestedQuantity" Member="RequestedQuantities">
    <Type Name="RequestedQuantity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequisitionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Figure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RequisitionItem_RequestedQuantity" Member="RequisitionItem" ThisKey="RequisitionItemId" OtherKey="Id" Type="RequisitionItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>